### ISSUE TITLE
Unable to download registered users only content (sofurry.com)

### ISSUE THREAD

**Issue by tj0mmi** [nikiroo/fanfix#1]
I am unable to download stories that are registered users only (NSFW content). This is on sofurry.com.
I have tried to input my account login in the configuration, but I am still unable to download the stories.

Is there something else I need to do?

**Comment by nikiroo** [comment]
Hello,

No, this was the correct procedure.

Maybe the website changed recently (this, sadly, is the nature of the web).
I check some websites now and then, but I probably missed that one (didn't try NSFW there recently).

It was a good idea to report an issue. Thanks!
I will have a look at it soon (Thursday or Friday, depending) and make a fix if I can.
I expect it to be easy (and thus quick).

Regards,
Niki

**Comment by nikiroo** [comment]
Ok, it should now be fixed in 2.0.3.

Also, note that you should clear the cache (Edit -> Clear cache) so not to get the same (incorrect) results after the update.

I also noticed that the layout of the stories on SoFurry is not so good.
But I'll fix that in the next version...

Please tell me if it is OK for you, too, so I can close the issue.

Regards,
Niki

**Comment by tj0mmi** [comment]
It works now! Thank you so much. (Sorry for the extremely late reply)
